### ISSUE TITLE
immutable version

### ISSUE THREAD

**Issue by huiwang** [hph/vigur#1]
hello, have you ever considered creating an immutable version ?

Immutability can make things simple to reason about especially in the context where i have to simulate things. It allows to travel back to the original state.

**Comment by hph** [comment]
Hi @huiwang. Some of the methods already support this, for instance, with:

``` javascript
const vector = new Vector(2, 3);
```

You can do:

``` javascript
vector.normalized
=> Vector {x: 0.5547001962252291, y: 0.8320502943378437}
vector
=> Vector {x: 2, y: 3}
```

Or you can do:

``` javascript
vector.normalize()
=> Vector {x: 0.5547001962252291, y: 0.8320502943378437}
vector
=> Vector {x: 0.5547001962252291, y: 0.8320502943378437}
```

Do you need something similar for `Vector#add`, `Vector#subtract`, etc?

**Comment by huiwang** [comment]
@hph , thx for pointing it out. I didn't notice that. Yes, for add, subtract and etc. But by immutability, i mean the whole object should not be modified regardless the method invoked on it.

I think we should create two separate class one immutable, the other mutable. This is similar to what have been done in scala for collections. http://docs.scala-lang.org/overviews/collections/overview.html 

I'll be happy to contribute :)

**Comment by hph** [comment]
@huiwang The getter methods clone the instance and return the result of the operation on the cloned instance, so the instance it's called on isn't mutated. Something similar should be possible with the other methods, for instance `Vector#added(anotherVector)` could return the operation for a cloned instance. I'm not sure I like the naming here, so maybe your suggestion would be better (`Vector.Immutable`?).

Contributions are welcome :smile_cat:

**Comment by hph** [comment]
Actually, if you need a version of any of the methods that doesn't mutate the object, you can always just use `Vector#clone`:

``` javascript
const vector = new Vector(2, 3)
vector.clone().add(2)
=> Vector {x: 4, y: 5}
vector
=> Vector {x: 2, y: 3}
```

**Comment by huiwang** [comment]
I won't call that immutability in a strict way. That's cloning an object and then modifying it. The object is cloneable and mutable.

**Comment by hph** [comment]
If you want the object to be immutable you can just subclass `Vector`:

``` javascript
Vector.Immutable = class Immutable extends Vector {
  constructor (x, y) {
    super(x, y);
    Object.freeze(this);
  }
}
```

And now your instances won't be mutable. If you want to do operations you're always going to have to create a new instance and return it (using `Vector#clone`).

**Comment by derhuerst** [comment]
That is still different from a library that embraces immutability without any workarounds and gives you new instances straight away. Also, keep in mind that `Object.freeze` does not freeze deeply.

**Comment by huiwang** [comment]
I stumbled upon a project called immutable.js which tries to provide immutable collections in javascript.

I may come back to this project but what I really want is an immutable physical engine to implement AI related algorithms.

Thx guys
